from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors


def _page_number(canvas, doc):
    canvas.saveState()
    canvas.setFont('Helvetica', 9)
    canvas.setFillColor(colors.HexColor('#1A5276'))
    canvas.drawRightString(A4[0] - 40, 20, f"Page {doc.page}")
    canvas.restoreState()


def generate_decision_pdf(user, analysis, decision_data, target_role, assessment):
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        title='PathMap Decision Summary',
        leftMargin=36,
        rightMargin=36,
        topMargin=48,
        bottomMargin=42
    )

    styles = getSampleStyleSheet()
    heading = ParagraphStyle(name='Heading', parent=styles['Heading1'], fontSize=20, textColor=colors.HexColor('#1A5276'), spaceAfter=12)
    subheading = ParagraphStyle(name='Subheading', parent=styles['Heading2'], fontSize=14, textColor=colors.HexColor('#2E86C1'), spaceAfter=8)
    body = ParagraphStyle(name='Body', parent=styles['BodyText'], fontSize=11, leading=15)
    muted = ParagraphStyle(name='Muted', parent=styles['BodyText'], fontSize=10, leading=14, textColor=colors.HexColor('#7F8C8D'))
    label = ParagraphStyle(name='Label', parent=styles['BodyText'], fontSize=10, textColor=colors.HexColor('#1A5276'), spaceAfter=4, leading=14)
    commitment_style = ParagraphStyle(name='Commitment', parent=styles['BodyText'], fontSize=12, leading=16, italic=True, textColor=colors.HexColor('#0D1B2A'))

    step_1 = decision_data.get('step_1', {})
    step_2 = decision_data.get('step_2', {})
    step_3 = decision_data.get('step_3', {})
    step_4 = decision_data.get('step_4', {})
    step_5 = decision_data.get('step_5', {})

    elements = []

    # Cover page
    elements.append(Spacer(1, 36))
    elements.append(Paragraph('PATHMAP', ParagraphStyle(name='Logo', parent=styles['Title'], fontSize=28, textColor=colors.HexColor('#1A5276'), alignment=0, spaceAfter=10, leading=32)))
    elements.append(Paragraph('Career Pivot Decision Summary', heading))
    elements.append(Paragraph(f"Generated for {user.first_name or user.display_name}", body))
    elements.append(Paragraph(f"Date: {datetime.utcnow().strftime('%d %b %Y')}", muted))
    elements.append(Spacer(1, 18))
    elements.append(Paragraph(f"Target Direction: {analysis.origin_role.title} → {target_role.title}", subheading))
    elements.append(Paragraph(
        f"Feasibility Score: {analysis.feasibility_score or 'N/A'}",
        ParagraphStyle(name='Feasibility', parent=styles['Heading3'], textColor=colors.HexColor('#2E86C1'), spaceAfter=12)
    ))
    elements.append(HRFlowable(width='100%', thickness=1, color=colors.HexColor('#1A5276'), spaceBefore=12, spaceAfter=24))
    elements.append(Paragraph('This document is private and confidential. Generated by PathMap.', muted))
    elements.append(PageBreak())

    # Page 2: Decision clarity
    elements.append(Paragraph('1. The Decision', heading))
    elements.append(Paragraph('What decision did you clarify?', label))
    elements.append(Paragraph(step_1.get('real_decision', 'Not provided'), body))
    elements.append(Spacer(1, 6))
    elements.append(Paragraph('Options considered:', label))
    option_items = step_1.get('decision_options', []) or []
    if option_items:
        options_table = Table([[f"• {opt}"] for opt in option_items], colWidths=[480])
        options_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('TOPPADDING', (0, 0), (-1, -1), 2),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 2)
        ]))
        elements.append(options_table)
    else:
        elements.append(Paragraph('No options provided.', muted))
    elements.append(Spacer(1, 8))
    elements.append(Paragraph('What is at stake?', label))
    elements.append(Paragraph(step_1.get('decision_stakes', 'Not provided'), body))
    elements.append(PageBreak())

    # Page 3: Values alignment
    elements.append(Paragraph('2. Values Alignment Check', heading))
    elements.append(Paragraph('Your top 5 work values were evaluated against each career option.', body))
    values_check = step_2.get('values_check', {}) or {}
    table_data = [['Value', 'Aligned Option']]
    for value_name, aligned_opt in values_check.items():
        table_data.append([value_name, aligned_opt or 'Not selected'])
    values_table = Table(table_data, colWidths=[200, 280])
    values_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#EBF5FB')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1A5276')),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CED4DA')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6)
    ]))
    elements.append(values_table)
    elements.append(Spacer(1, 10))
    elements.append(Paragraph('Options that scored highest on your most important values are the strongest fit.', muted))
    elements.append(PageBreak())

    # Page 4: Assumptions
    elements.append(Paragraph('3. Key Assumptions', heading))
    assumptions = step_3.get('assumptions', []) or []
    confidence_map = {
        1: 'Very Uncertain',
        2: 'Uncertain',
        3: 'Somewhat Confident',
        4: 'Confident',
        5: 'Very Confident'
    }
    if assumptions:
        assumption_rows = [['Option', 'Assumption', 'Confidence']]
        for item in assumptions:
            confidence_text = confidence_map.get(int(item.get('confidence', 3)), 'Somewhat Confident')
            assumption_rows.append([item.get('option', ''), item.get('assumption', ''), confidence_text])
        assumption_table = Table(assumption_rows, colWidths=[120, 320, 80])
        assumption_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#EBF5FB')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1A5276')),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CED4DA')),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6)
        ]))
        elements.append(assumption_table)
    else:
        elements.append(Paragraph('No assumptions captured.', muted))
    elements.append(Spacer(1, 8))
    elements.append(Paragraph('The assumptions you are most uncertain about represent the key risks in this decision.', body))
    elements.append(PageBreak())

    # Page 5: Time travel
    elements.append(Paragraph('4. The 10/10/10 Perspective Test', heading))
    ten_data = [
        ('In 10 days, this decision will feel like:', step_4.get('ten_days', 'Not provided')),
        ('In 10 months, this decision will mean:', step_4.get('ten_months', 'Not provided')),
        ('In 10 years, this decision will have been:', step_4.get('ten_years', 'Not provided'))
    ]
    for label_text, content in ten_data:
        box = Table([[Paragraph(label_text, label)], [Paragraph(content, body)]], colWidths=[500])
        box.setStyle(TableStyle([
            ('BOX', (0, 0), (-1, -1), 0.8, colors.HexColor('#2E86C1')),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#EBF5FB')),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 6)
        ]))
        elements.append(box)
        elements.append(Spacer(1, 10))
    elements.append(PageBreak())

    # Page 6: Commitment
    elements.append(Paragraph('5. Your Commitment', heading))
    elements.append(Paragraph('I am committing to:', label))
    elements.append(Paragraph(step_5.get('committed_direction', 'Not provided'), body))
    elements.append(Spacer(1, 6))
    elements.append(Paragraph('My personal note:', label))
    elements.append(Paragraph(step_5.get('commitment_note', 'Not provided'), body))
    elements.append(Spacer(1, 12))

    commitment_text = decision_data.get('ai_commitment_statement', 'PathMap AI could not generate the statement at this time.')
    commitment_table = Table(
        [
            [Paragraph('Your PathMap Commitment Statement', ParagraphStyle(name='CommitLabel', parent=styles['Heading4'], textColor=colors.HexColor('#F0B429')))],
            [Paragraph(commitment_text, commitment_style)]
        ],
        colWidths=[500]
    )
    commitment_table.setStyle(TableStyle([
        ('BOX', (0, 0), (-1, -1), 1.2, colors.HexColor('#F0B429')),
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#FFF6E0')),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10)
    ]))
    elements.append(commitment_table)
    elements.append(Spacer(1, 12))
    elements.append(Paragraph('Signed: _____________________________     Date: _____________________________', body))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(f'This commitment statement was generated with PathMap AI on {datetime.utcnow().strftime("%d %b %Y")}. Review it whenever you need to reconnect with your decision.', muted))

    doc.build(elements, onFirstPage=_page_number, onLaterPages=_page_number)
    buffer.seek(0)
    return buffer
